### ISSUE TITLE
Implement git actions for node-backend

### ISSUE THREAD

**Issue by raffleberry** [raffleberry/cartel#18]
- when a PR is submitted, git actions should run `npm test` on node-backend folder.

**Comment by yalefresne** [comment]
Hello @raffleberry, i would like to work on it if you wanna.

**Comment by raffleberry** [comment]
Sure go ahead @yalefresne

**Comment by yalefresne** [comment]
I am not sure #20 is necessary, i can use [mongodb-action](https://github.com/supercharge/mongodb-github-action)

**Comment by yalefresne** [comment]
You can see run of github action [here](https://github.com/yalefresne/cartel/actions/runs/3184107942)

**Comment by raffleberry** [comment]
> I am not sure #20 is necessary, i can use [mongodb-action](https://github.com/supercharge/mongodb-github-action)

good point. But still it takes extra ~15 seconds for github actions to complete.

Lets keep [mongodb-action](https://github.com/supercharge/mongodb-github-action) for now. I'll change it later if I run out of free tier usage.

**Comment by yalefresne** [comment]
You're right.  
During my test [billing time](https://github.com/yalefresne/cartel/actions/runs/3189390208/usage) for the github action running time was 0 second, but we never now, keep eye on time usage.  

#23 is ready
