### ISSUE TITLE
Implement in-memory mongodb for CI tests

### ISSUE THREAD

**Issue by raffleberry** [raffleberry/cartel#20]
Currently running `npm test ` on `node-backend`, expects mongodb to be installed on dev machine.
For #18 we need all tests to be testable in isolation, without any dependencies 

possible solutions:-
- in memory mongodb for testing.
- add tests that dont include any db interactions.

**Comment by Siddharth9890** [comment]
I can work on this if you can assign it to me

**Comment by raffleberry** [comment]
@Siddharth9890 sure.
